name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.0' # Updated to Qt 6.7.0
        host: 'windows'
        target: 'desktop'
        dir: 'C:/Qt'
        tools: 'tools_qtcreator, tools_cmake, tools_ninja'

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_PREFIX_PATH=C:/Qt/6.7.0/msvc2019_64

    - name: Build
      run: cmake --build build --config Release

    - name: Run tests
      run: ctest --output-on-failure
      working-directory: build
