name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.7.0' # Adjust this to the version of Qt you're using
        host: 'windows'
        target: 'desktop'
        dir: 'C:/Qt'
        tools: 'tools_qtcreator, tools_cmake, tools_ninja'

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_PREFIX_PATH=C:/Qt/6.7.0/msvc2019_64

    - name: Build
      run: cmake --build build --config Release

    - name: Run tests
      run: ctest --output-on-failure
      working-directory: build

    - name: Package the application
      run: |
        # Find the executable
        set executable=build\Release\Advanced-Tic-Tac-Toe.exe
        
        # Use windeployqt to bundle dependencies
        C:\Qt\6.7.0\msvc2019_64\bin\windeployqt.exe %executable%

        # Create a zip file of the bundled executable
        powershell Compress-Archive -Path build\Release\* -DestinationPath build\Release\Advanced-Tic-Tac-Toe.zip

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Advanced-Tic-Tac-Toe
        path: build/Release/Advanced-Tic-Tac-Toe.zip
