name: Build and Deploy on Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qt6-base-dev qt6-tools-dev qt6-tools-dev-tools libgl1-mesa-dev build-essential cmake
        sudo apt-get install -y appimagetool
        sudo apt-get install -y libfuse2

   - name: Configure with CMake
      run: cmake -B build -S . -DCMAKE_PREFIX_PATH=/usr/lib/qt6

    - name: Build with CMake
      run: cmake --build build --config Release

    - name: Download linuxdeployqt
      run: |
        wget -c https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
        chmod +x linuxdeployqt-continuous-x86_64.AppImage

    - name: Create AppImage
      run: |
        ./linuxdeployqt-continuous-x86_64.AppImage build/your_executable -appimage

    - name: Archive AppImage
      uses: actions/upload-artifact@v3
      with:
        name: AppImage
        path: ./build/*.AppImage
