#--------------------------------------------------------------------------------
# Workflow configuration
#--------------------------------------------------------------------------------

name: Build
on:
  push:               # Run on push to any branch
    branches:
      - main        # Change this to your main branch name if different
  pull_request:       # Run on pull-request

#--------------------------------------------------------------------------------
# Define application name & version
#--------------------------------------------------------------------------------

env:
  VERSION: "1.0.0"
  EXECUTABLE: "QtApp"  # Change this to your executable name
  APPLICATION: "Qt App"  # Change this to your application name
  CMAKE_PROJECT: "CMakeLists.txt"

#--------------------------------------------------------------------------------
# Workflow jobs (GNU/Linux, macOS & Windows)
#--------------------------------------------------------------------------------

jobs:
  #
  # GNU/Linux build (we run on Ubuntu 20.04)
  #
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      #
      # Checkout the repository
      #
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      #
      # Install Qt
      #
      - name: Install Qt
        uses: jurplel/install-qt-action@v2

      #
      # Install CMake and other dependencies
      #
      - name: Install CMake and other dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build libgl1-mesa-dev libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0 libzstd-dev

      #
      # Configure and build using CMake (using a different build directory)
      #
      - name: Configure and build
        run: |
          mkdir build_github_actions
          cd build_github_actions
          cmake -G "Ninja" ..
          cmake --build .

      #
      # Package the application (AppImage)
      #
      - name: Package AppImage
        run: |
          mkdir appdir
          make install DESTDIR=appdir
          wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" -O linuxdeployqt
          chmod a+x linuxdeployqt
          ./linuxdeployqt appdir/usr/share/applications/*.desktop -appimage -bundle-non-qt-libs

      #
      # Rename and upload the AppImage artifact
      #
      - name: Upload AppImage
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.EXECUTABLE}}-${{env.VERSION}}-Linux.AppImage
          path: ${{env.EXECUTABLE}}-${{env.VERSION}}-Linux.AppImage

  #
  # macOS build
  #
  build-mac:
    runs-on: macos-latest
    steps:
      #
      # Checkout the repository
      #
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      #
      # Install Qt
      #
      - name: Install Qt
        uses: jurplel/install-qt-action@v2

      #
      # Install CMake
      #
      - name: Install CMake
        run: brew install cmake

      #
      # Configure and build using CMake (using a different build directory)
      #
      - name: Configure and build
        run: |
          mkdir build_github_actions
          cd build_github_actions
          cmake -G "Ninja" ..
          cmake --build .

      #
      # Package and zip the macOS application
      #
      - name: Package macOS app
        run: |
          macdeployqt ${EXECUTABLE}.app -always-overwrite
          mv ${EXECUTABLE}.app ${APPLICATION}.app
          ditto -c -k --sequesterRsrc --keepParent ${APPLICATION}.app ${EXECUTABLE}-${VERSION}-macOS.zip
          rm -rf ${APPLICATION}.app  # Clean up macOS application directory

      #
      # Upload the macOS ZIP artifact
      #
      - name: Upload ZIP
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.EXECUTABLE}}-${{env.VERSION}}-macOS.zip
          path: ${{env.EXECUTABLE}}-${{env.VERSION}}-macOS.zip

  #
  # Windows build
  #
  build-windows:
    runs-on: windows-latest
    steps:
      #
      # Checkout the repository
      #
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      #
      # Configure MSVC
      #
      - name: Configure MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          spectre: true

      #
      # Install Qt
      #
      - name: Install Qt
        uses: jurplel/install-qt-action@v2

      #
      # Install CMake and other dependencies using Scoop
      #
      - name: Install CMake and dependencies
        run: |
          scoop install cmake ninja

      #
      # Configure and build using CMake (using a different build directory)
      #
      - name: Configure and build
        run: |
          mkdir build_github_actions
          cd build_github_actions
          cmake -G "Ninja" ..
          cmake --build .

      #
      # Deploy and package the Windows application using NSIS
      #
      - name: Deploy and package Windows app
        run: |
          mkdir bin
          move build\\${EXECUTABLE}.exe bin
          windeployqt bin\\${EXECUTABLE}.exe --compiler-runtime
          mkdir "${APPLICATION}"
          move bin "${APPLICATION}"
          xcopy deploy\\windows\\resources\\icon.ico "${APPLICATION}"

          move "${APPLICATION}" deploy\\windows\\nsis\\
          cd deploy\\windows\\nsis
          makensis /X"SetCompressor /FINAL lzma" setup.nsi
          ren *.exe ${EXECUTABLE}-${VERSION}-Windows.exe

      #
      # Upload the Windows installer artifact
      #
      - name: Upload NSIS installer
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.EXECUTABLE}}-${{env.VERSION}}-Windows.exe
          path: deploy/windows/nsis/${{env.EXECUTABLE}}-${{env.VERSION}}-Windows.exe
