name: Build and Deploy on Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qt6-base-dev qt6-tools-dev qt6-tools-dev-tools libgl1-mesa-dev build-essential cmake

    - name: Configure with CMake
      run: cmake -B build -S . -DCMAKE_PREFIX_PATH=/usr/lib/qt6

    - name: Build with CMake
      run: cmake --build build --config Release

    - name: Download tools
      run: |
        wget -c https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
        chmod +x linuxdeployqt-continuous-x86_64.AppImage
        wget -c https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage

    - name: Create Dockerfile
      run: |
        echo "FROM ubuntu:20.04" > Dockerfile
        echo "RUN apt-get update && apt-get install -y qt6-base-dev qt6-tools-dev qt6-tools-dev-tools libgl1-mesa-dev build-essential cmake libfuse2 wget" >> Dockerfile
        echo "COPY . /workspace" >> Dockerfile
        echo "WORKDIR /workspace" >> Dockerfile
        echo "RUN wget -c https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage && chmod +x linuxdeployqt-continuous-x86_64.AppImage" >> Dockerfile
        echo "RUN wget -c https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage && chmod +x appimagetool-x86_64.AppImage" >> Dockerfile
        echo "RUN cmake -B build -S . -DCMAKE_PREFIX_PATH=/usr/lib/qt6" >> Dockerfile
        echo "RUN cmake --build build --config Release" >> Dockerfile
        echo "RUN ./linuxdeployqt-continuous-x86_64.AppImage build/your_executable -appimage" >> Dockerfile

    - name: Build Docker image and create AppImage
      run: |
        docker build -t appimage-builder .
        docker run --rm -v $PWD:/workspace appimage-builder

    - name: Archive AppImage
      uses: actions/upload-artifact@v3
      with:
        name: AppImage
        path: ./build/*.AppImage
