name: CI
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        setup-python: 'false'
    - name: Configure with CMake
      run: cmake -B build -S . -DCMAKE_PREFIX_PATH=$env:Qt6_DIR
    - name: Build with CMake
      run: cmake --build build --config Release
    - name: Create executable
      run: |
        cd build\Release
        windeployqt.exe --qmldir . Advanced-Tic-Tac-Toe.exe
    - name: Zip executable
      run: |
        cd build\Release
        7z a -tzip Advanced-Tic-Tac-Toe.zip *
    - name: Archive executable
      uses: actions/upload-artifact@v3
      with:
        name: Windows-Executable
        path: build/Release/Advanced-Tic-Tac-Toe.zip

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: Windows-Executable
    - name: Generate release notes
      run: |
        echo "# Release notes for ${{ github.ref_name }}" > RELEASE_NOTES.md
        echo "## Changes" >> RELEASE_NOTES.md
        git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty=format:"- %s" >> RELEASE_NOTES.md
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: Advanced-Tic-Tac-Toe.zip
        body_path: RELEASE_NOTES.md
        token: ${{ secrets.PAT_TOKEN }}
