name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'

    - name: Install dependencies
      run: |
        choco install ninja cmake --install-arguments='"ADD_CMAKE_TO_PATH=System"'

    - name: Configure CMake
      run: cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release

    - name: Build with CMake
      run: cmake --build build --config Release

    - name: Package executable
      run: cmake --install build --prefix package

    - name: Upload Release Asset
      uses: actions/upload-artifact@v3
      with:
        name: Advanced-Tic-Tac-Toe
        path: package/

  release:
    runs-on: windows-latest
    needs: build

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: Advanced-Tic-Tac-Toe
        path: .

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./package/
        asset_name: Advanced-Tic-Tac-Toe.exe
        asset_content_type: application/octet-stream
